### ISSUE TITLE
port 0

### ISSUE THREAD

**Issue by ShockWave2048** [code-orchestra/colt-as#21]
Выдает такую live ошибку после запуска на анроиде:

> error loading file from: http://192.168.1.31:0/colt/livecoding/package_2.swf

Порт что ли неправильно сконфигурирован на сборке?
(desktop AIR тоже 0-й порт)

**Comment by ShockWave2048** [comment]
Разобрался, в файле проекта. Ходил мимо раз десять.)
Закрывать или это баг?

**Comment by SlavaRa** [comment]
Если сам опишешь решение, то можно закрывать

**Comment by ShockWave2048** [comment]
## Решение:

В файле проекта ( Project.colt ) первая строчка содержит хмл атрибут

> projectPort='0'
> поправить на любой доступный 
> projectPort='9000'
