### ISSUE TITLE
Инструкции по сборке

### ISSUE THREAD

**Issue by kolombet** [code-orchestra/colt-as#27]
Хотелось бы собрать это добро. Но без инструкций по сборке это очень проблематично. Никаких maven/gradle файлов нету, открываю idea проект 14 идеей, проект пустой, конфигураций сборки нету..

**Comment by kolombet** [comment]
А, нашел. Инструкции по сборке в другом репозитории. https://github.com/code-orchestra/colt-build

**Comment by boozook** [comment]
:+1:
