### ISSUE TITLE
COLT.IO livecoding для as3 теперь бесплатен?

### ISSUE THREAD

**Issue by vasivas** [code-orchestra/colt-as#4]
На глаза попалось сообщение, в котором говорится, что за COLT-IO теперь не нужно платить,
но на Вашем сайте я не нашел подтверждающей информации и почта у Вас не работает.

По этому спрашиваю здесь - это правда?

**Comment by SlavaRa** [comment]
а не могли вы показать сообщение, которое попалось Вам на глаза?

**Comment by vasivas** [comment]
Да, конечно - http://www.flasher.ru/forum/showpost.php?p=1181644&postcount=4

**Comment by SlavaRa** [comment]
Ну так вы пишите в репозиторий проекта colt-as(только для ас3!), который, да, теперь бесплатен, и вы можете подключиться к разработке или просто использовать его целях,
единственно что пока сборка немного неудобна, но это в самое ближайшее время решиться.. буквально 1-2 дня подождать еще

**Comment by vasivas** [comment]
Хм.. Вы меня запутали :) Что такое ac3? И я интересуюсь flash-actionscript3, это он стал бесплатен?

**Comment by ShockWave2048** [comment]
В заголовке написано "COLT.IO livecoding для as3..." (ActionScript 3)
COLT - теперь бесплатный, вернее опенсорс
ас3 - всю жизнь бесплатный

**Comment by SlavaRa** [comment]
Colt для ActionScript3 теперь в опенсорсе

**Comment by vasivas** [comment]
Но опенсорс ведь не означает что он бесплатный? Или означает что бесплатный?

Вы меня за "непонимание" извините, я просто не могу въехать.

**Comment by ShockWave2048** [comment]
исходники в свободном доступе, скачивай, настраивай и компилируй

**Comment by vasivas** [comment]
Походу понял :) colt-as, это отдельный проект, который создается на базе COLT.IO, верно?
И если предыдущие верно, то colt-as будет готов со дня на день и будет бесплатен?
